name: Deploy to ECS Fargate with Terraform

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment (dev, qa, prod)'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
      approve_apply:
        description: 'Approve Terraform Apply'
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: my-app
      ECS_CLUSTER: my-app-cluster
      ECS_SERVICE: my-app-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init
        working-directory: environments/${{github.event.inputs.environment}}

      - name: Plan Terraform Changes
        run: terraform plan
        working-directory: environments/${{github.event.inputs.environment}}

      - name: Apply Terraform Changes
        run: terraform apply -var-file=terraform.tfvars -auto-approve
        working-directory: environments/${{github.event.inputs.environment}}
